### ISSUE TITLE
Does the load generator assume the target core has no existing load?

### ISSUE THREAD

**Issue by AndySchroder** [GaetanoCarlucci/CPULoadGenerator#10]
Does the load generator assume the target core has no existing load? Meaning, does the target load generated by this script shoot to maintain a total load of the target CPU, or does it just add the generated load to the existing load on the target CPU?

**Comment by GaetanoCarlucci** [comment]
The generator uses psutil.cpu_percent to measure the load which returns a float representing the current system-wide CPU utilization as a percentage.
