### ISSUE TITLE
Exception "ImportError: dynamic module does not define init function (init_path)"

### ISSUE THREAD

**Issue by aliomarabdelazim** [GaetanoCarlucci/CPULoadGenerator#5]
Hello, I am trying to use your tool to generate certain load to CPU at certain time intervals, I just cloned the repository and installed the required Python libraries. When I tried to run as the example I got this error 

ImportError: dynamic module does not define init function (init_path)

I am using CentOS 7.3 and Python 3.5.1

**Comment by GaetanoCarlucci** [comment]
Hello,

the tool has been written for Python 2.7.
Please try to change the interpreter.

Best regards,
Gaetano.

2018-05-15 18:15 GMT+02:00 aliomarabdelazim <notifications@github.com>:

**Comment by aliomarabdelazim** [comment]
Thank you very, It used 2.7 and it works. 

Thanks again
